version: '3.8'
services:
  pg:
    image: cardstack/pg-test
    ports:
      - '5432'
    networks:
      - cs
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  cardstack:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "/cardstack/packages/cardhost/init.sh"
    restart: always
    environment:
      - PGHOST=pg
      - DEFAULT_REALM_URL
      - META_REALM_URL
      - HUB_URL
      - DEV_DIR
    ports:
      - '3000:3000'
      - '4200:4200'
    networks:
      - cs
    depends_on:
      pg:
        condition: service_healthy
networks:
  cs:
    driver: bridge
